export const data = [
  {
    id: 1,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 2,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 3,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 4,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 5,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 6,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 7,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 8,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 9,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 10,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
  {
    id: 11,
    name: "Amit Hariyale",
    role: "Admin",
    status: "Active",
    date: "04/10/2013",
    image: "images/image.jpg",
  },
];
